# Generated by Django 4.2.10 on 2026-06-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_hackathonteam_hackathonsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='components',
            field=models.TextField(blank=True, help_text="What's included - certificates, materials, etc. One per line"),
        ),
        migrations.AddField(
            model_name='event',
            name='food_details',
            field=models.CharField(blank=True, help_text='e.g. Breakfast & Lunch, Snacks, etc.', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='has_food',
            field=models.BooleanField(default=False, help_text='Food provided'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_payment',
            field=models.BooleanField(default=False, help_text='Payment required'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_details',
            field=models.CharField(blank=True, help_text='e.g. 50,000 TZS, Free for members', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_details',
            field=models.TextField(blank=True, help_text='Building, room number, directions, etc.'),
        ),
    ]
