# Generated by Django 4.2.10 on 2026-06-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_event_components_event_food_details_event_has_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for call/text', max_length=30),
        ),
    ]
