# Generated by Django 4.2.10 on 2026-06-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_eventspeaker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagendaitem',
            name='resource_file',
            field=models.FileField(blank=True, help_text='PDF, Excel, Jupyter notebook, etc.', null=True, upload_to='agenda_resources/'),
        ),
        migrations.AddField(
            model_name='eventagendaitem',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Link to codebase, slides, or external resource'),
        ),
    ]
