# Generated by Django 4.2.10 on 2026-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_eventchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchatmessage',
            name='reply_to',
            field=models.CharField(blank=True, help_text='ID of message being replied to', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='reply_user',
            field=models.CharField(blank=True, help_text='Username of replied message author', max_length=100, null=True),
        ),
    ]
