# Generated by Django 4.2.10 on 2026-06-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_eventchatmessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchatmessage',
            name='reply_snippet',
            field=models.CharField(blank=True, help_text='Snippet of replied message', max_length=200, null=True),
        ),
    ]
