# Generated by Django 4.2.10 on 2026-06-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_eventchatmessage_reply_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
